config/routes.rb
Rails.application.routes.draw do
  
  
  root to: "home#home"
  
  
  # resources :projects, only: [:new, :create]

  get 'users/sign_in'
  post 'users/login'
  
  resources :users, only: [:new, :create, :show]

  resources :users do
    resources :projects, only: [:index, :show, :new, :create]
  end


  get 'users/sign_out'
  post 'users/logout' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :project
    belongs_to :user

end

app/models/project.rb
class Project < ApplicationRecord

    belongs_to :user
    has_many :comments

    def create_comment(text)
        @user_id = self.user_id
        self.comments.create({user_id: @user_id, text: text})
    end


end

app/models/user.rb
class User < ApplicationRecord

    has_many :projects
    has_many :comments, through: :projects

    has_secure_password

    def say_hello
        puts "Hello World"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in, :current_user

    private

    def login_user user
        session[:current_user] = user
    end

    def logout_user
        session.clear
    end

    def logged_in
        session[:current_user]
    end

    def current_user
        session[:current_user] || nil
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = Project.where({user_id: params[:user_id]})
    
  end

  def new
  end

  def create
  end

  def show
    @project = Project.find_by_id(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @params = params["user"]
    if @params["password"] == @params["confirm_password"]
      @user = User.create(user_params)
      login_user @user
      redirect_to user_projects_path(@user)
    else
      redirect_to new_user_path
    end
    
  end
  
  
  def sign_in
    @user = User.new
  end
  
  def login
    @user = User.find_by({email: params[:user][:email]})
    if @user and @user.authenticate params[:user][:password] 
      login_user @user
      redirect_to user_path(@user)
    else
      redirect_to users_sign_in_path
    end
    
  end
  
  def logout
    logout_user
    redirect_to '/'
  end
  
  def show
    @user = User.find_by_id(params[:id])
    @projects = @user.projects
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/home.html.erb
<h1>Welcome!</h1>

app/views/layouts/_nav.html.erb


<nav>
    <% if !logged_in %>
        <div class="nav-item">
            <%= button_to "Sign In", users_sign_in_path, method: "get" %>
        </div>
        
        <div class="nav-item">
            <%= button_to "Sign Up", new_user_path, method: "get" %>
        </div>

    <% end %>
    

    <% if logged_in %>
        <div class="nav-item">
            <%= button_to "Logout", users_logout_path, method: 'post' %>
        </div>
    <% end %>
    
    <% if logged_in %>
        <div class="nav-item">
            <%= button_to "My Projects", "/users/#{current_user["id"]}/projects/", method: 'get' %>
        </div>
    <% end %>
    
    <% if logged_in %>
        <div class="nav-item">
            <%= button_to "New Project", "/users/#{current_user["id"]}/projects/new", method: 'get' %>
        </div>
    <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "layouts/nav" %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_projects_list.html.erb


<% @projects.each do |project| %>

    <div project-box>
        <h2><%= project.title %></h2>
    </div>

<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb


<h1>My Projects</h1>

<%= render "projects_list", locals: {projects: @projects} %>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>This is the project show page</h1>

<h2><%= @project.title %></h2>

app/views/users/_render_projects.html.erb


<ul>

    <% @projects.each do |project| %>
        
        <li><%= link_to "#{project.title}", user_project_path(project) %></li>    
        
    <% end %>

</ul>

app/views/users/_sign_in_form.html.erb

<%= form_for @user, url: users_login_path do |f| %>
    <h3>Sign In:</h3>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.submit "Sign In" %>

<% end %>

app/views/users/_user_form.html.erb

<%= form_for @user  do |f| %>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br>
    
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br>
    
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <% if !@user.first_name %>
        <%= f.label :confirm_password %><br>
        <%= f.password_field :confirm_password %><br>

    <% end %>

    <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= render "user_form", locals: {user: @user} %>

app/views/users/show.html.erb
<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>

<%= render "render_projects", locals: {projects: @projects} %>

app/views/users/sign_in.html.erb


<%= render "sign_in_form" %>